---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.3/charts/library/common/values.schema.json
controllers:
  main:
    revisionHistoryLimit: 1

    pod:
      runtimeClassName: nvidia

    containers:
      main:
        image:
          repository: fyb3roptik/threadfin
          tag: 1.0.24-nvidia
          pullPolicy: IfNotPresent

        env:
          TZ: '{{ .Values.global.TZ }}'
  
  guide2go:
    enabled: true
    type: cronjob
    cronjob:
       schedule: "0 4 * * *"
    containers:
      main:
        image:
          repository: chuchodavids/guide2go
          tag: stable
          pullPolicy: IfNotPresent
        
        command:
        - guide2go
        - --config
        - /home/threadfin/conf/guide2go/WA63873-DITV819.yaml

        env:
          TZ: '{{ .Values.global.TZ }}'
      
service:
  main:
    controller: main
    ports:
      http:
        port: 34400

ingress:
  main:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: '{{ .Chart.Name }}.brush{{ .Values.global.altDomainRe }}'
      paths:
        - path: /
          pathType: Prefix
          service:
            identifier: main
            port: http
    tls:
      - secretName: '{{ .Chart.Name }}-tls'
        hosts:
          - '{{ .Chart.Name }}.brush{{ .Values.global.altDomainRe }}'

persistence:
  config:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 20Gi
    accessMode: ReadWriteOnce
    retain: true
    globalMounts:
      - path: /home/threadfin/conf
  buffertmp:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /buffertmp
