# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
image:
  repository: ghcr.io/dblk/tinshop
  tag: latest
  pullPolicy: IfNotPresent

controller:
  revisionHistoryLimit: 1

service:
  main:
    ports:
      http:
        port: 3000

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: '{{ .Chart.Name }}.{{ .Values.global.domain }}'
      paths:
      - path: /
        pathType: Prefix      
    tls:
      - secretName: '{{ .Chart.Name }}-tls'
        hosts:
          - '{{ .Chart.Name }}.{{ .Values.global.domain }}'

persistence:
  config:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 4Gi
    accessMode: ReadWriteOnce
    retain: true
  games:
    enabled: true
    type: hostPath
    hostPath: /mnt/sol/switch/nsz
    mountPath: /games

podSecurityContext:
  runAsUser: 1002
  runAsGroup: 1004
  fsGroup: 1004
  fsGroupChangePolicy: OnRootMismatch
