apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Chart.Name }}-checkheaders
  namespace: {{ .Release.Namespace }}
spec:
  plugin:
    checkheaders:
      headers:
        - header:
          name: UID
          matchtype: one
          values:
            - "UID"
