global:
  repo: https://github.com/jbruns/ArgoCD-SCALE.git
  branch: main
  domain: wavebe.am
  altDomainHome: bruns.house
  TZ: America/Los_Angeles

  applicationSets:
  - common
  - media
  - home
  - monitoring
    
  storage:
    pools: 
      argo-zfspv-fast: luna/argo/pv
      argo-zfspv-slow: andromeda/argo/pv

  metallb:
    defaultPool: 172.16.20.0-172.16.20.254
