apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sonarr-exportarr-env
  namespace: argo-media
spec:
  encryptedData:
    API_KEY: AgBmXs2hik+R8RXzwfWmT6VqwUdOzZxR24pHId/0e5AUwA0B/n1LJpTr2fHnGkkl3wM08GpXi/GZGc3v2iZhcypefta/chtXxU4n8DpFJ9ZKCfqW5f1zabJtXxNlsG0+U74tlxJmZfIqRJaPSm+yqRDOkMpKo+vd+SUCU1O0eMXMfzTnS4TJtKb4vRgqzBIMYDekl4OYAHNM1CL1/TK+RY1TxrHcbOTngA/e++CVhp5K+merqZFT17hInwcdCBIyoW5B0dEC2Hq0aArGifqfScXB4TWhqmgQHXxWPHf23XGiac8fl16NNOYojojbkXB4WzCf+LD5ecBqtNPF0ZJ6x0+sXuRVRvdtHEL1QMI6H00wcjSrU2pmWx829Ebzms9RPlsvvsBi4F6GKqM4N9hpidOj4rV1KWSmTDt06owMXia8CjBjtewICsaudXhWe9wFHstMT80fyDWXZOR81QWzW23t+4LK8bBVi6ZkaXg5kHA684WYjD/kKGRVoUg99PUCYLUIYsS3dUldih+iRXDvFsP5BDaMP/INxRqiVrRP1WfoOdDk4DNDg6BFtXYzCw6tLGgn9PqKce0S+EGBO81bGjpSFS9XzjjCw7D8WJdpbi53qWplMQBgQsk2akzohPZ3xUFhmeSRUzo+KIYYacksWMfsdP2HQ2AMxucl4P+dKpCAw7B7+BCWX39Um+Uq/C8qUzWcXi1OEU5/XbPZDxaMJ6T+ax5n2SanyyiX6zs5Z0RY7w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: sonarr-exportarr-env
      namespace: argo-media
    type: Opaque

