authentik:
  error_reporting: false
  redis:
    host: redis-master.argo-common

envValueFrom:
  AUTHENTIK_SECRET_KEY:
    secretKeyRef:
      name: authentik-env
      key: AUTHENTIK_SECRET_KEY
  AUTHENTIK_POSTGRESQL__PASSWORD:
    secretKeyRef:
      name: authentik-env
      key: POSTGRES_PASSWORD

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: 'vault.{{ .Values.global.altDomainHome }}'
      paths:
      - path: /
        pathType: Prefix      
    tls:
      - secretName: '{{ .Chart.Name }}-tls'
        hosts:
          - '{{ .Chart.Name }}.{{ .Values.global.domain }}'

redis:
  enabled: false

postgresql:
  auth:
    existingSecret: postgresql-auth