apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-codeserver-http
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`ha-config.{{ .Values.global.altDomainHome }}`)
      kind: Rule
      services:
        - name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-addon-codeserver
          port: codeserver
  tls:
    secretName: {{ .Chart.Name }}-codeserver-tls
