# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
controllers:
  main:
    revisionHistoryLimit: 1

    containers:
      main:
        image:
          repository: eclipse-mosquitto
          tag: 2.0.18
          pullPolicy: IfNotPresent

service:
  main:
    ports:
      http:
        enabled: false
      mqtt:
        enabled: true
        port: 1883

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: mqtt
    hosts:
    - host: 'mqtt.{{ .Values.global.altDomainHome }}'
      paths:
        - path: /
          pathType: Prefix
          service:
            name: main
            port: mqtt

persistence:
  data:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 5Gi
    accessMode: ReadWriteOnce
    retain: true
    globalMounts:
      - path: /mosquitto/data

  configinc:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 100Mi
    accessMode: ReadWriteOnce
    retain: true
    globalMounts:
      - path: /mosquitto/configinc
  
  config:
    enabled: true
    type: configMap
    name: mosquitto-config
    globalMounts:
      - path: /mosquitto/config

auth:
  enabled: true
addListener: true
perListenerSettings: false