# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
image:
  repository: eclipse-mosquitto
  tag: 2.0.18

controller:
  revisionHistoryLimit: 1

service:
  main:
    ports:
      http:
        enabled: false
      mqtt:
        enabled: true
        port: 1883

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: mqtt
    hosts:
    - host: 'mqtt.{{ .Values.global.altDomainHome }}'
      paths:
      - path: /
        pathType: Prefix

persistence:
  data:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 5Gi
    mountPath: /mosquitto/data
    accessMode: ReadWriteOnce
    retain: true
  configinc:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 100Mi
    mountPath: /mosquitto/configinc
    accessMode: ReadWriteOnce
    retain: true

auth:
  enabled: true
addListener: true
perListenerSettings: false