---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.3/charts/library/common/values.schema.json
controllers:
  main:
    revisionHistoryLimit: 1

    containers:
      main:
        image:
          repository: alturismo/xteve_guide2go
          tag: latest
          pullPolicy: IfNotPresent

        env:
          TZ: '{{ .Values.global.TZ }}'

        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5
        
service:
  main:
    controller: main
    ports:
      http:
        port: 34400

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: '{{ .Chart.Name }}.brush{{ .Values.global.altDomainRe }}'
      paths:
        - path: /
          pathType: Prefix
          service:
            identifier: main
            port: http
    tls:
      - secretName: '{{ .Chart.Name }}-tls'
        hosts:
          - '{{ .Chart.Name }}.brush{{ .Values.global.altDomainRe }}'

persistence:
  xtevehome:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 10Gi
    accessMode: ReadWriteOnce
    retain: true
    globalMounts:
      - path: /root/.xteve
  config:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 1Gi
    accessMode: ReadWriteOnce
    retain: true
  buffertmp:
    enabled: true
    type: emptyDir