---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.3/charts/library/common/values.schema.json
controllers:
  main:
    revisionHistoryLimit: 1

    containers:
      main:
        image:
          repository: ghcr.io/onedr0p/tautulli
          tag: 2.13.4
          pullPolicy: IfNotPresent

        env:
          TZ: '{{ .Values.global.TZ }}'

        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8181

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: '{{ .Chart.Name }}.{{ .Values.global.domain }}'
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: main
          port: http
    tls:
      - secretName: '{{ .Chart.Name }}-tls'
        hosts:
          - '{{ .Chart.Name }}.{{ .Values.global.domain }}'

persistence:
  config:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 10Gi
    accessMode: ReadWriteOnce
    retain: true

defaultPodOptions:
  securityContext:
    runAsUser: 1001
    runAsGroup: 1002
    fsGroup: 1002
    fsGroupChangePolicy: "OnRootMismatch"
