{{- range $svcName := tuple "alertmanager" "prometheus" "grafana" -}}
{{- if index $.Values "kube-prometheus-stack" $svcName "ingress" "enabled" -}}
{{- with index $.Values "kube-prometheus-stack" $svcName -}}
{{- $svcPort := .service.port }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata: 
  name: "{{ $svcName }}-{{ $svcPort }}"
  namespace: {{ $.Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    {{- range .ingress.hosts }}
    - match: Host(`{{ tpl . $ }}`)
      kind: Rule
      {{- if ne $svcName "grafana" }}
      middlewares:
        - name: "{{ $svcName }}-auth"
      {{- end }}
      services:
        {{- if eq $svcName "grafana"}}
        - name: "{{ $.Release.Name }}-{{ $svcName }}"
        {{- else }}
        - name: "{{ $.Chart.Name }}-{{ $svcName }}"
        {{- end }}
          port: {{ $svcPort }}
    {{- end }}
  tls:
    secretName: {{ $svcName }}-tls
{{- end }}
{{- if ne $svcName "grafana"}}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ $svcName }}-auth
  namespace: {{ $.Release.Namespace }}
spec:
  basicAuth:
    secret: {{ $svcName }}-dashboard
{{- end }}
{{- end }}
{{- end }}
