# https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml

# Disable deployment - we do not need it for this chart.
controllers:
  main:
    enabled: false

# Disable service objects rendered by the common chart; we will generate our own in the following proxy instances.
service:
  main:
    enabled: false

instances:
  - name: minio-console
    enabled: true
    ip: 172.16.2.5
    port: 9003
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        cert-manager.io/revision-history-limit: '1'
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: 'minio-console.wavebe.am'
      paths:
        - path: /
          pathType: Prefix      
      tls:
        - secretName: 'reverse-proxy-minio-console-tls'
          hosts:
            - 'minio-console.wavebe.am'

  - name: minio
    enabled: true
    ip: 172.16.2.5
    port: 9001
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        cert-manager.io/revision-history-limit: '1'
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
        - host: 'minio.wavebe.am'
      paths:
        - path: /
          pathType: Prefix      
      tls:
        - secretName: 'reverse-proxy-minio-tls'
          hosts:
            - 'minio.wavebe.am'