# https://github.com/nextcloud/helm/blob/master/charts/nextcloud/values.yaml
nextcloud:
  image:
    tag: 25.0.2
    pullPolicy: IfNotPresent
    
  ingress:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/priority: 99
    hosts:
    - host: nextcloud.bruns.house
      paths:
      - path: /
        pathType: Prefix      
    tls:
      - secretName: nextcloud-tls
        hosts:
          - nextcloud.bruns.house
    
  nextcloud:
    host: nextcloud.bruns.house
    existingSecret:
      enabled: true
      secretName: nextcloud-admin
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password
      smtpUsernameKey: smtp-username
      smtpPasswordKey: smtp-password
    mail:
      enabled: true
      fromAddress: nextcloud
      domain: bruns.house
      smtp:
        host: smtp.comcast.net
        port: 25
        secure: ''
    extraEnv:
      - name: REDIS_HOST
        value: redis-master.argo-common
      - name: OVERWRITEHOST
        value: nextcloud.bruns.house
      - name: OVERWRITEPROTOCOL
        value: https
      - name: TRUSTED_PROXIES
        value: 172.17.0.0/16
    phpConfigs:
      zzz-maximums.ini: |-
        upload_max_filesize=512M
        post_max_size=550M
        memory_limit=1G
  
  internalDatabase:
    enabled: false
  
  externalDatabase:
    enabled: true
    host: mariadb.argo-common
    database: nextclouddb
    existingSecret:
      enabled: true
      secretName: nextcloud-database
      usernameKey: nextcloud-username
      passwordKey: nextcloud-password
    
  cronjob:
    enabled: true

  persistence:
    enabled: true
    storageClass: argo-zfspv-slow
    size: 4Ti

  metrics:
    enabled: true
    https: true
