# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
controllers:
  main:
    revisionHistoryLimit: 1

    containers:
      main:
        image:
          repository: docker.io/vaultwarden/server
          tag: 1.32.0
          pullPolicy: IfNotPresent

        env:
          # https://github.com/dani-garcia/vaultwarden/blob/main/.env.template
          DOMAIN: 'https://vault.{{ .Values.global.altDomainHome }}'
          HELO_NAME: 'vault.{{ .Values.global.altDomainHome }}'

        envFrom:
          - secretRef:
              name: vaultwarden-env

        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5

service:
  main:
    controller: main
    ports:
      http:
        port: 8080
        targetPort: 80

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: 'vault.{{ .Values.global.altDomainHome }}'
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - secretName: '{{ .Chart.Name }}-tls'
        hosts:
          - 'vault.{{ .Values.global.altDomainHome }}'

persistence:
  data:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 100Gi
    accessMode: ReadWriteOnce
    retain: true
