apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-http
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`{{ .Values.nextcloud.nextcloud.host }}`) && PathPrefix(`/s`)
      kind: Rule
      priority: 1
      middlewares:
        - name: {{ .Chart.Name }}-secheaders
          namespace: {{ .Release.Namespace }}
      services:
        - name: {{ .Chart.Name }}
          port: http
    - match: Host(`{{ .Values.nextcloud.nextcloud.host }}`)
      kind: Rule
      priority: 2
      middlewares:
        - name: {{ .Chart.Name }}-well-known
          namespace: {{ .Release.Namespace }}
        - name: {{ .Chart.Name }}-secheaders
          namespace: {{ .Release.Namespace }}
        - name: crowdsec-traefik-bouncer
          namespace: argo-common
      services:
        - name: {{ .Chart.Name }}
          port: http
  tls:
    secretName: {{ .Chart.Name }}-tls
