# https://docs.nextcloud.com/server/21/go.php?to=admin-setup-well-known-URL
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Chart.Name }}-well-known
  namespace: {{ .Release.Namespace }}
spec:
  redirectRegex:
    regex: https://(.*)/.well-known/(card|cal)dav
    replacement: https://{{ .Values.nextcloud.nextcloud.host }}/remote.php/dav/
    permanent: true
