{{- range (index .Values "instances") }}
{{- $svcName := printf "%s-%s" (include "bjw-s.common.lib.chart.names.name" $) .name }}
{{- $svcPort := .port -}}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: "{{ $svcName }}-{{ $svcPort }}"
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" $ | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    {{- range .ingress.hosts }}
    - match: Host(`{{ tpl .host $ }}`)
      kind: Rule
      services:
        - name: {{ $svcName }}
          port: {{ $svcPort }}
    {{- end }}
  tls:
    secretName: {{ $svcName }}-tls
{{ end }}
