{{- include "bjw-s.common.loader.init" . -}}
{{- range .Values.instances }}
{{- if or ( not ( hasKey . "enabled" ) ) .enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bjw-s.common.lib.chart.names.name" $ }}-{{ .name }}
  labels:
    {{- include "bjw-s.common.lib.metadata.allLabels" $ | nindent 4 }}
spec:
  {{- if .externalName }}
  type: ExternalName
  externalName: {{ .externalName }}
  {{- end }}
  ports:
    - protocol: TCP
      port: {{ .port | default 80 }}
---
{{- end }}
{{- end }}
