apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-http
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`vault.{{ .Values.global.altDomainHome }}`)
      kind: Rule
      services:
        - name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}
          port: http
  tls:
    secretName: {{ .Chart.Name }}-tls
