# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
image:
  repository: homeassistant/home-assistant
  tag: 2023.10.5
  pullPolicy: IfNotPresent
  
env:
  TZ: '{{ .Values.global.TZ }}'  

controller:
  revisionHistoryLimit: 1

service:
  main:
    ports:
      http:
        port: 8123

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: 'ha.{{ .Values.global.altDomainHome }}'
      paths:
      - path: /
        pathType: Prefix      
    tls:
      - secretName: '{{ .Chart.Name }}-tls'
        hosts:
          - 'ha.{{ .Values.global.altDomainHome }}'

persistence:
  config:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 50Gi
    accessMode: ReadWriteOnce
    retain: true

addons:
  codeserver:
    enabled: true
    workingDir: "/config"
    args:
    - --user-data-dir
    - "/config/.vscode"
    - --extensions-dir
    - "/config/.vscode"
    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        cert-manager.io/revision-history-limit: '1'
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      hosts:
      - host: 'ha-config.{{ .Values.global.altDomainHome }}'
        paths:
        - path: /
          pathType: Prefix      
      tls:
        - secretName: '{{ .Chart.Name }}-codeserver-tls'
          hosts:
            - 'ha-config.{{ .Values.global.altDomainHome }}'
    volumeMounts:
    - name: config
      mountPath: /config
