# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
controllers:
  main:
    revisionHistoryLimit: 1

    containers:
      main:
        image:
          repository: homeassistant/home-assistant
          tag: 2023.12.3
          pullPolicy: IfNotPresent
          
        env:
          TZ: '{{ .Values.global.TZ }}'
      
      codeserver:
        dependsOn: main
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.19.1
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
          - --port
          - "8081"
          - "/config"

service:
  main:
    ports:
      http:
        port: 8123
  
  codeserver:
    controller: main
    ports:
      http:
        port: 8081

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: 'ha.{{ .Values.global.altDomainHome }}'
        paths:
          - path: /
            pathType: Prefix
            service:
              name: main
    tls:
      - secretName: '{{ .Chart.Name }}-tls'
        hosts:
          - 'ha.{{ .Values.global.altDomainHome }}'
  
  codeserver:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
      - host: 'ha-config.{{ .Values.global.altDomainHome }}'
        paths:
          - path: /
            pathType: Prefix
            service:
              name: codeserver
    tls:
      - secretName: '{{ .Chart.Name }}-codeserver-tls'
        hosts:
          - 'ha-config.{{ .Values.global.altDomainHome }}'

persistence:
  config:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 50Gi
    accessMode: ReadWriteOnce
    retain: true
