---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.2.1/charts/library/common/values.schema.json
controllers:
  main:
    revisionHistoryLimit: 1

    containers:
      main:
        image:
          repository: senexcrenshaw/streammaster
          tag: 0.14.6
          pullPolicy: IfNotPresent

        env:
          PUID: '1001'
          PGID: '1002'


service:
  main:
    controller: main
    ports:
      http:
        port: 7095

ingress:
  main:
    enabled: true
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: '{{ .Chart.Name }}.brush{{ .Values.global.altDomainRe }}'
      paths:
        - path: /
          pathType: Prefix
          service:
            identifier: main
            port: http
    tls:
      - secretName: '{{ .Chart.Name }}-tls'
        hosts:
          - '{{ .Chart.Name }}.brush{{ .Values.global.altDomainRe }}'

persistence:
  config:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 20Gi
    accessMode: ReadWriteOnce
    retain: true

defaultPodOptions:
  securityContext:
    fsGroup: 1002
    fsGroupChangePolicy: "OnRootMismatch"