---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.3/charts/library/common/values.schema.json
controllers:
  main:
    revisionHistoryLimit: 1
    
    pod:
      runtimeClassName: nvidia
      
    containers:
      main:
        image:
          repository: emby/embyserver
          tag: 4.8.7.0
          pullPolicy: IfNotPresent
          
        env:
          UID: '1001'
          GID: '1002'
        
        resources:
          requests:
            nvidia.com/gpu: 1
            cpu: 200m
            memory: 1024Mi
          limits:
            nvidia.com/gpu: 1
            memory: 3072Mi

        probes:
          liveness:
            enabled: true
            custom: true
            type: TCP
            spec:
              initialDelaySeconds: 10
              failureThreshold: 3
              periodSeconds: 30
              tcpSocket:
                port: 32800
          readiness:
            enabled: true
            custom: true
            type: TCP
            spec:
              initialDelaySeconds: 10
              failureThreshold: 3
              periodSeconds: 30              
              tcpSocket:
                port: 32800
          startup:
            enabled: true
            custom: true
            type: TCP
            spec:
              failureThreshold: 30
              periodSeconds: 5
              tcpSocket:
                port: 32800

service:
  main:
    controller: main
    type: NodePort
    ports:
      http:
        enabled: true
        port: 32800
        protocol: TCP
        nodePort: 32800
      https:
        enabled: true
        port: 32900
        protocol: TCP
        nodePort: 32900
    externalTrafficPolicy: Local

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: '{{ .Chart.Name }}.{{ .Values.global.domain }}'
      paths:
      - path: /
        pathType: Prefix
        service:
          identifier: main
          port: http
    tls:
      - secretName: '{{ .Chart.Name }}-tls'
        hosts:
          - '{{ .Chart.Name }}.{{ .Values.global.domain }}'

persistence:
  config:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 300Gi
    accessMode: ReadWriteOnce
    retain: true
  transcode:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 300Gi
    accessMode: ReadWriteOnce
    retain: true
  data:
    enabled: true
    type: hostPath
    hostPath: /mnt/andromeda/media
    globalMounts:
      - path: /data
        readOnly: true

defaultPodOptions:
  securityContext:
    fsGroup: 1002
    fsGroupChangePolicy: "OnRootMismatch"
    supplementalGroups:
      - 107 # render
      - 44 # video