# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
controllers:
  main:
    revisionHistoryLimit: 1

    containers:
      main:
        image:
          repository: emby/embyserver
          tag: latest
          pullPolicy: IfNotPresent
          
        env:
          UID: 1001
          GID: 1002
          GIDLIST: 107,44
          NVIDIA_VISIBLE_DEVICES: all
          NVIDIA_DRIVER_CAPABILITIES: compute,video,utility

service:
  main:
    ports:
      http:
        port: 8096

ingress:
  main:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
      cert-manager.io/revision-history-limit: '1'
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
    hosts:
    - host: '{{ .Chart.Name }}.{{ .Values.global.domain }}'
      paths:
      - path: /
        pathType: Prefix
        service:
          name: main
    tls:
      - secretName: '{{ .Chart.Name }}-tls'
        hosts:
          - '{{ .Chart.Name }}.{{ .Values.global.domain }}'

persistence:
  config:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 300Gi
    accessMode: ReadWriteOnce
    retain: true
  data:
    enabled: true
    type: hostPath
    hostPath: /mnt/andromeda/media
    globalMounts:
      - path: /data
        readOnly: true

defaultPodOptions:
  securityContext:
    runAsUser: 1001
    runAsGroup: 1002
    fsGroup: 1002
    fsGroupChangePolicy: "OnRootMismatch"
    supplementalGroups:
      - 107 # render
      - 44 # video
